#! /usr/bin/env python
import sys
from bsddb import btopen
from shelve import BsdDbShelf

def load(filename):
    db = BsdDbShelf(btopen(filename, 'r'))
    return db

if __name__ == '__main__':
    import sys
    db = load(sys.argv[1])

    for k, (out, err) in db.iteritems():
        sys.stdout.write(out)
