#! /usr/bin/env python
"""
Run a filter ex-post-facto.

This is useful if your filter function is misbehaving on the zounds-worker
computers for reasons that you don't care to debug ;).
"""
import filters
filter = filters.top_matches_only

from bsddb import btopen
from shelve import BsdDbShelf

import sys
_db = btopen(sys.argv[1], 'r')
db = BsdDbShelf(_db)

_db2 = btopen(sys.argv[2], 'c')
outdb = BsdDbShelf(_db2)

for n, k in enumerate(_db):
    if n % 100 == 0:
        print '...', n
    v = db[k]
    v = filter(v)
    outdb[k] = v
