#! /usr/bin/env python
import sys
from bsddb import btopen
from shelve import BsdDbShelf
from cStringIO import StringIO

sys.path.insert(0, '/u/t/dev/hmmer3parser')
import parse_hmmer3

if __name__ == '__main__':
    import sys
    _db = btopen(sys.argv[1], 'r')
    db = BsdDbShelf(_db)

    n = 0
    for k in _db:
        out, err = db[k]
        
        n += 1
        
        hits = parse_hmmer3.parse_hmmscan_scoreForCompleteSeq(StringIO(out))
        if hits:
            print hits
