#! /usr/bin/env python
import sys
import xmlrpclib
from subprocess import Popen, PIPE
from blastparser import parse_string
from cPickle import dumps

DEFAULT_SERVER='http://iorich.caltech.edu:5678'

VERBOSE=True

def do_blast(program, against_db, extra_args, name, seq):
    seqs = ">%s\n%s\n" % (name, seq,)

    p = Popen("blastall -d %s -p %s %s" % (against_db, program, extra_args),
              shell=True, stdout=PIPE, stderr=PIPE, stdin=PIPE)
    (out, err) = p.communicate(seqs)

    return out, err

def parse_blast(out):
    records = parse_string(out)
    records = list(records)
    return records

def handle_sequences(program, against_db, extra_args, seqs):
    z = []
    for n, (name, seq) in enumerate(seqs):
        if VERBOSE:
            print 'starting BLAST %d of %d...' % (n + 1, len(seqs))
            
        out, err = do_blast(program, against_db, extra_args, name, seq)

        if VERBOSE:
            print '   ... finished.'

        records = parse_blast(out)

        # error?
        if len(records) == 0:
            print '--\n** sequence: %s\n%s' % (name, out)
            print >>sys.stderr, '--\n** sequence: %s\n%s' % (name, err)
            record = ()
        else:
            assert len(records) == 1
            record = records[0]

        yield name, record

if __name__ == '__main__':
    server_url = DEFAULT_SERVER
    if len(sys.argv) == 2:
        server_url = sys.argv[1]
        print 'Using alternate zounds server:', server_url

    s = xmlrpclib.Server(server_url)

    (chunksize, n_chunks, dump_frequency) = s.get_parameters()

    results = []
    for i in range(n_chunks):
        if VERBOSE:
            print 'asking for %d sequences' % (chunksize,)
            
        x = s.retrieve_sequences(chunksize)
        if not x:
            break
        
        program, against_db, extra_args, seqs = x
        for name, record in handle_sequences(program, against_db,
                                             extra_args, seqs):
            pickle = dumps(record)
            results.append((name, xmlrpclib.Binary(pickle)))

            if len(results) >= dump_frequency:
                if VERBOSE:
                    print 'dumping %d results' % (len(results),)
                s.deposit_results(results)
                results = []

    if results:
        if VERBOSE:
            print 'dumping %d results' % (len(results),)
        s.deposit_results(results)
