#! /usr/bin/env python
import sys
import xmlrpclib

DUMP_FREQUENCY=10
DEFAULT_SERVER='http://iorich.caltech.edu:5678'

if __name__ == '__main__':
    server_url = DEFAULT_SERVER
    if len(sys.argv) == 2:
        server_url = sys.argv[1]
        print 'Using alternate zounds server:', server_url

    s = xmlrpclib.Server(server_url)
    print s.estimate_undone()
